/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesfoodorder;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
import java.sql.*;
public class Bayar extends javax.swing.JFrame {
Connection cn;
int kembalian;
    /**
     * Creates new form Bayar
     */
    public Bayar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Bayar (String data){
        initComponents();
        this.setLocationRelativeTo(null);
        String text = data;
        btnbayar.setEnabled(false);
        txttotal.setText(""+text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txttotal = new javax.swing.JLabel();
        btnbayar = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Retroica", 0, 24)); // NOI18N
        jLabel1.setText("Pembayaran");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Retroica", 0, 14)); // NOI18N
        jLabel2.setText("Total Bayar");

        jLabel3.setFont(new java.awt.Font("Retroica", 0, 14)); // NOI18N
        jLabel3.setText("Bayar");

        jLabel4.setFont(new java.awt.Font("Retroica", 0, 14)); // NOI18N
        jLabel4.setText("Kembalian");

        txtkembalian.setFont(new java.awt.Font("Retroica", 0, 14)); // NOI18N
        txtkembalian.setText("0");

        txtbayar.setFont(new java.awt.Font("Retroica", 0, 14)); // NOI18N
        txtbayar.setText(" ");
        txtbayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtbayarMousePressed(evt);
            }
        });
        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbayarKeyPressed(evt);
            }
        });

        txttotal.setFont(new java.awt.Font("Retroica", 0, 14)); // NOI18N
        txttotal.setText("0");

        btnbayar.setBackground(new java.awt.Color(255, 153, 51));
        btnbayar.setText("Bayar");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addComponent(txtkembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttotal)))
                            .addComponent(btnbayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnkembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)))))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnkembali)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttotal))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnbayar)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkembalian))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
       
    }//GEN-LAST:event_txtbayarActionPerformed

    public void connection(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3307/janjikita", "root", "");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Koneksi close");
        }
    }
    
    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        connection();
        
        try{
                    File struk = new File("Struck.txt");
                try {
                    FileWriter tulis = new FileWriter("Struck.txt");

                    tulis.write("========================== Janji Kita ==========================\n======================== Coffe & Toast =========================\n\n");
                    
                    PreparedStatement ps = cn.prepareStatement("select * from keranjang");
                    ResultSet rs = ps.executeQuery();
                    tulis.write("Produk\t\t\t\tKuantitas\tSub Total \n");
                    tulis.write("----------------------------------------------------------------\n");
                    while (rs.next()){
                        tulis.write(rs.getString(2)+ "\t\t" + rs.getInt(3)+"\t\t" +rs.getInt(4)+"\n");
                    }
                    tulis.write("----------------------------------------------------------------\n");
                    tulis.write("Grand Total\t\t\t\t\t" +txttotal.getText()+"\n");
                    tulis.write("Bayar\t\t\t\t\t\t" +txtbayar.getText()+"\n");
                    tulis.write("Kembalian\t\t\t\t\t" +kembalian+ "\n\n");
                    tulis.write("======================= Terima Kasih <3 ======================\n" +
"========= Semoga kamu cepat bertemu dengan jodohmu ===========");
                    tulis.close();
                }catch (IOException e) {
                    System.out.println("error");
                    e.printStackTrace();
                }
                PreparedStatement ps = cn.prepareStatement("delete from keranjang");
                ps.execute();
                cn.close();
                JOptionPane.showMessageDialog(null,"Lunas, terimakasih (: ");
                this.dispose();
                new Main().setVisible(true);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnbayarActionPerformed

    private void txtbayarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbayarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarMousePressed

    private void txtbayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyPressed
        int cash = Integer.parseInt(txtbayar.getText());
       int total = Integer.parseInt(txttotal.getText());
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (cash < total){
                JOptionPane.showMessageDialog(null, "Kurang cuan");
            } else{
                kembalian = cash - total;
               txtkembalian.setText(""+kembalian);
               btnbayar.setEnabled(true);
            }
           
       }
        
    }//GEN-LAST:event_txtbayarKeyPressed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btnkembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JLabel txtkembalian;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
