/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesfoodorder;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AFRIZAL SY
 */
public class Produk extends javax.swing.JFrame {
Connection cn;
byte[] gambar;
byte[] bitarray = null;
String path;
    public byte[] getgambar(){
        return gambar;
    }
    public byte[] getgambar(int id){
        try{
            PreparedStatement ps = cn.prepareStatement("select gambar from produk where id_produk like '"+id+"' ");
            ps.execute();
            ResultSet rs = ps.executeQuery();
            byte[] file = null;
            while(rs.next()){
                file =  rs.getBytes("gambar");
            }
            return file;
        } catch (Exception ex){
            
        }
        return null;
    }
    public void setgambar(byte[] gambar){
        this.gambar = gambar;
    }
    public Produk() {
        initComponents();
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
        
        
        connection();
        loadrecord(tabelproduk);
        btnsave.setEnabled(true);
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);
        btnclear.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelproduk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtproduk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        btngbr = new javax.swing.JButton();
        txtgbr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pangbr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tabelproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelprodukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelproduk);

        jLabel1.setFont(new java.awt.Font("Retroica", 0, 24)); // NOI18N
        jLabel1.setText("Janji Kita Janji Bersama");
        jLabel1.setToolTipText("");

        txtproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodukActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Harga");

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnsave.setText("Tambah");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        txtid.setText("-");

        btngbr.setText("Pilih Gambar");
        btngbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngbrActionPerformed(evt);
            }
        });

        txtgbr.setEditable(false);
        txtgbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgbrActionPerformed(evt);
            }
        });

        jLabel6.setText("File");

        pangbr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnkembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(187, 187, 187))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(40, 40, 40)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtid)
                                            .addComponent(txtproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)
                                .addComponent(pangbr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btngbr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtgbr)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnkembali))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtid))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(pangbr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtgbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btngbr)))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void ambilgambar(){
        try{
            int id = Integer.parseInt(txtid.getText());
            byte[] img = getgambar(id);
            BufferedImage file = ImageIO.read(new ByteArrayInputStream(img));
            ImageIcon icon = new ImageIcon(resize(pangbr.getWidth(), pangbr.getHeight(), file));
            pangbr.setIcon(icon);
        } catch (Exception ex){
            
        }
    }
    public void loadrecord(JTable tabelproduk){
        try{
                PreparedStatement ps = cn.prepareStatement("select * from produk");
                ResultSet rs = ps.executeQuery();
                DefaultTableModel model = (DefaultTableModel)tabelproduk.getModel();
                model.setRowCount(0);
                Object[] row;
                while (rs.next()){
                    row = new Object[3];
                    row[0] = rs.getInt(1);
                    row[1] = rs.getString(2);
                    row[2] = rs.getInt(3);
                    model.addRow(row);
                }
                ps.execute();
//                ambilgambar();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    private void tabelprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelprodukMouseClicked
        btnsave.setEnabled(false);
        btndelete.setEnabled(true);
        btnupdate.setEnabled(true);
        int rowIndex = tabelproduk.getSelectedRow();
        txtid.setText(tabelproduk.getValueAt(rowIndex,0).toString());
        txtproduk.setText(tabelproduk.getValueAt(rowIndex,1).toString());
        txtharga.setText(tabelproduk.getValueAt(rowIndex,2).toString());
        ambilgambar();
        
    }//GEN-LAST:event_tabelprodukMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
      connection();
        
        try{
            String id = txtid.getText();
            if(id.equals("-")){
                JOptionPane.showMessageDialog(null, "Tidak ada data dipilih");
            } else {
                PreparedStatement ps = cn.prepareStatement("delete from produk where id_produk like '"+id+"'");
                ps.execute();
                cn.close();
                JOptionPane.showMessageDialog(null, "Berhasil Dihapus");
                txtid.setText("-");
            txtproduk.setText("");
            txtharga.setText("");
            }
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        new Option().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed
    public void connection(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3307/janjikita", "root", "");
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Koneksi close");
        }
    }
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        connection();
        String prod = txtproduk.getText();
        String harga = txtharga.getText();
//        String gambar = txtgbr.getText();
        
        try{
            PreparedStatement ps = cn.prepareStatement("insert into produk (nama_produk, harga, gambar) values (?,?,?)");
            ps.setString(1, prod);
            ps.setString(2, harga);
            if(!txtgbr.getText().equals("")){
                ByteArrayOutputStream output = new ByteArrayOutputStream();
                File img = new File(path);
                FileInputStream input = new FileInputStream(img);
                try{
                    byte[] buf = new byte[1024];
                    for (int readbyte;(readbyte=input.read(buf))!=-1;){
                        output.write(buf,0,readbyte);
                    }
                    bitarray = output.toByteArray();
                    setgambar(bitarray);
                    pangbr.setIcon(null);
                } catch (Exception ex){
                }
            ps.setBytes(3, getgambar());
            }
            ps.execute();
            cn.close();
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
            txtid.setText("-");
            txtproduk.setText("");
            txtharga.setText("");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        connection();
        btngbr.setEnabled(true);
        try{
            
            String prod = txtproduk.getText();
            String harga = txtharga.getText();
            String id = txtid.getText();
            if(!txtgbr.getText().equals("")){
                ByteArrayOutputStream output = new ByteArrayOutputStream();
                File img = new File(path);
                FileInputStream input = new FileInputStream(img);
                try{
                    byte[] buf = new byte[1024];
                    for (int readbyte;(readbyte=input.read(buf))!=-1;){
                        output.write(buf,0,readbyte);
                    }
                    bitarray = output.toByteArray();
                    setgambar(bitarray);
//                    pangbr.setIcon(null);
                } catch (Exception ex){
                }
            }
            PreparedStatement ps = cn.prepareStatement("update produk set nama_produk = '"+prod+"' , harga = '"+harga+"', gambar = ? where id_produk like '"+id+"'");
            ps.setBytes(1, getgambar());
            ps.execute();
            cn.close();
            JOptionPane.showMessageDialog(null, "Berhasil Diubah");
            txtid.setText("-");
            txtproduk.setText("");
            txtharga.setText("");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtid.setText("-");
        pangbr.setIcon(null);
        txtgbr.setText("");
        txtproduk.setText("");
        txtharga.setText("");
        btnsave.setEnabled(true);
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);
    }//GEN-LAST:event_btnclearActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodukActionPerformed

    private void btngbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngbrActionPerformed
        Image images;
        
        JFileChooser gbr = new JFileChooser(System.getProperty("user.home"));
        gbr.setFileFilter(new FileNameExtensionFilter("jpg|png", "jpg", "png"));
        gbr.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if(gbr.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file = gbr.getSelectedFile();
            try{
                images = ImageIO.read(file);
                
                ImageIcon icon = new ImageIcon(resize(pangbr.getWidth(), pangbr.getHeight(), images));
                pangbr.setIcon(icon);
                path = file.getAbsolutePath();
                txtgbr.setText(file.getName());
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btngbrActionPerformed

    private Image resize(int w, int h, Image img){
        BufferedImage bufimg = new BufferedImage(w,h, BufferedImage.TYPE_INT_RGB);
        Graphics2D dimensi = bufimg.createGraphics();
        dimensi.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        dimensi.drawImage(img, 0,0,w,h, null);
        dimensi.dispose();
        return bufimg;
    }
    private void txtgbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgbrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btngbr;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pangbr;
    private javax.swing.JTable tabelproduk;
    private javax.swing.JTextField txtgbr;
    private javax.swing.JTextField txtharga;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtproduk;
    // End of variables declaration//GEN-END:variables
}
